### ISSUE TITLE
watcher.py isn't targetting 3.5

### ISSUE THREAD

**Issue by jcrowgey** [CaliDog/certstream-server-python#13]
The README says:

> Note Running the server requires at least python 3.5, as we use the new async/await syntax internally

But certstream/watcher.py seems to use features introduced python3.6:

<pre>
$ python3.5 run_server.py 
Traceback (most recent call last):
  File "run_server.py", line 1, in <module>
    import certstream
  File "/home/j/src/certstream-server/certstream/__init__.py", line 9, in <module>
    from certstream.watcher import TransparencyWatcher
  File "/home/j/src/certstream-server/certstream/watcher.py", line 148
    yield certificates['entries']
    ^
SyntaxError: 'yield' inside async function
</pre>

https://www.python.org/dev/peps/pep-0525/

**Comment by Fitblip** [comment]
Hey @jcrowgey - Thanks for the heads up! This is fixed with PR #10
